import Head from 'next/head'
import Image from 'next/image'

import styled from 'styled-components'

const Nav = styled.div`
  
`;

const Container = styled.div`
  
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Biblioteca de Componentes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav>

      </Nav>
      <Container>
        
      </Container>
    </>
  )
}
