import React, { useState } from 'react';

import Head from 'next/head'
import Image from 'next/image'

import styled from 'styled-components'

import Nav from '../components/Nav'
import Content from '../components/Content'

const Container = styled.div`
  display: flex;
  padding: 2vh 2vw;
`;

export default function Home() {
  
  const [isNavActive, setNavActive] = useState('');

  const handleToggleNav = () => {
    setNavActive(!isNavActive);
  };

  return (
    <>
      <Head>
        <title>Biblioteca de Componentes</title>
        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Nav handleToggleNav={handleToggleNav} isNavActive={isNavActive}/>
        <Content handleToggleNav={handleToggleNav} isNavActive={isNavActive}/>
      </Container>
    </>
  )
}
